### ISSUE TITLE
ESMPy?

### ISSUE THREAD

**Issue by j08lue** [jhamman/xmap#1]
Very cool and valuable feature you are adding to `xarray`, @jhamman.

The `KDTree` approach is very flexible and fast and even works for unstructured data. Perhaps one could extend this plugin to work for non-geographic coordinates, too, that do not need Cartesian transformation?

Beyond that, would it be worthwhile to look into interfacing [ESMPy](https://www.earthsystemcog.org/projects/esmpy/) also? That would be much more powerful for gridded data and add conservative gridding methods. 

I have been looking at the ESMPy project from a distance for a long time. I just checked again and it seems to be very mature now, like [this tutorial shows](https://github.com/nawendt/esmpy-tutorial/blob/master/esmpy_tutorial.ipynb)... I am just curious what you think about this.

**Comment by jhamman** [comment]
@j08lue - thanks for the comments. I'm glad you like some of the ideas here.

To be honest, I'm not sure how far we'll end up taking `xmap`. A simplified kdtree will eventually make it into xarray ([issue](https://github.com/pydata/xarray/issues/475)). 

One possible successor to this package is [`xESMF`](https://github.com/JiaweiZhuang/xESMF). That package is being developed by @JiaweiZhuang and has some real potential. There are some outstanding issues that the author is working on but it may be a natural successor to xmap.

Contributions would be welcome for https://github.com/pydata/xarray/issues/475 or at xESMF.

**Comment by j08lue** [comment]
Thanks for the explanation, @jhamman, and for pointing me to `xESMF`. I will keep track of things and contribute if I can.
